---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: dcagatay/ubuntu-dind:20.04
    pre_build_image: true
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
